#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace qdRealBusService
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="web")]
	public partial class qdRealBusDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertRealBus(RealBus instance);
    partial void UpdateRealBus(RealBus instance);
    partial void DeleteRealBus(RealBus instance);
    #endregion
		
		public qdRealBusDataClassesDataContext() : 
				base(global::qdRealBusService.Properties.Settings.Default.webConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public qdRealBusDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public qdRealBusDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public qdRealBusDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public qdRealBusDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<visualData> visualData
		{
			get
			{
				return this.GetTable<visualData>();
			}
		}
		
		public System.Data.Linq.Table<RealBus> RealBus
		{
			get
			{
				return this.GetTable<RealBus>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.visualData")]
	public partial class visualData
	{
		
		private int _id;
		
		private string _busLineName;
		
		private string _BusStopName;
		
		private string _stationname;
		
		private System.Nullable<int> _stopnumber;
		
		private string _timeCount;
		
		private System.Nullable<int> _timespan;
		
		private System.Nullable<double> _distance;
		
		private System.Nullable<double> _speed;
		
		private string _week;
		
		private System.Nullable<double> _startlng;
		
		private System.Nullable<double> _starlat;
		
		private System.Nullable<double> _endlng;
		
		private System.Nullable<double> _endlat;
		
		private string _street;
		
		private string _district;
		
		public visualData()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_busLineName", DbType="NVarChar(50)")]
		public string busLineName
		{
			get
			{
				return this._busLineName;
			}
			set
			{
				if ((this._busLineName != value))
				{
					this._busLineName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BusStopName", DbType="NVarChar(50)")]
		public string BusStopName
		{
			get
			{
				return this._BusStopName;
			}
			set
			{
				if ((this._BusStopName != value))
				{
					this._BusStopName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stationname", DbType="NVarChar(50)")]
		public string stationname
		{
			get
			{
				return this._stationname;
			}
			set
			{
				if ((this._stationname != value))
				{
					this._stationname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stopnumber", DbType="Int")]
		public System.Nullable<int> stopnumber
		{
			get
			{
				return this._stopnumber;
			}
			set
			{
				if ((this._stopnumber != value))
				{
					this._stopnumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timeCount", DbType="NVarChar(50)")]
		public string timeCount
		{
			get
			{
				return this._timeCount;
			}
			set
			{
				if ((this._timeCount != value))
				{
					this._timeCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timespan", DbType="Int")]
		public System.Nullable<int> timespan
		{
			get
			{
				return this._timespan;
			}
			set
			{
				if ((this._timespan != value))
				{
					this._timespan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_distance", DbType="Float")]
		public System.Nullable<double> distance
		{
			get
			{
				return this._distance;
			}
			set
			{
				if ((this._distance != value))
				{
					this._distance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_speed", DbType="Float")]
		public System.Nullable<double> speed
		{
			get
			{
				return this._speed;
			}
			set
			{
				if ((this._speed != value))
				{
					this._speed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_week", DbType="NVarChar(50)")]
		public string week
		{
			get
			{
				return this._week;
			}
			set
			{
				if ((this._week != value))
				{
					this._week = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startlng", DbType="Float")]
		public System.Nullable<double> startlng
		{
			get
			{
				return this._startlng;
			}
			set
			{
				if ((this._startlng != value))
				{
					this._startlng = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_starlat", DbType="Float")]
		public System.Nullable<double> starlat
		{
			get
			{
				return this._starlat;
			}
			set
			{
				if ((this._starlat != value))
				{
					this._starlat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endlng", DbType="Float")]
		public System.Nullable<double> endlng
		{
			get
			{
				return this._endlng;
			}
			set
			{
				if ((this._endlng != value))
				{
					this._endlng = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endlat", DbType="Float")]
		public System.Nullable<double> endlat
		{
			get
			{
				return this._endlat;
			}
			set
			{
				if ((this._endlat != value))
				{
					this._endlat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_street", DbType="NVarChar(50)")]
		public string street
		{
			get
			{
				return this._street;
			}
			set
			{
				if ((this._street != value))
				{
					this._street = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_district", DbType="NVarChar(50)")]
		public string district
		{
			get
			{
				return this._district;
			}
			set
			{
				if ((this._district != value))
				{
					this._district = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RealBus")]
	public partial class RealBus : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _busLineName;
		
		private string _BusStopsName;
		
		private string _stationname;
		
		private string _actdatetime;
		
		private string _stationnum;
		
		private string _busselfid;
		
		private string _lng;
		
		private string _lat;
		
		private System.Nullable<int> _passger;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnbusLineNameChanging(string value);
    partial void OnbusLineNameChanged();
    partial void OnBusStopsNameChanging(string value);
    partial void OnBusStopsNameChanged();
    partial void OnstationnameChanging(string value);
    partial void OnstationnameChanged();
    partial void OnactdatetimeChanging(string value);
    partial void OnactdatetimeChanged();
    partial void OnstationnumChanging(string value);
    partial void OnstationnumChanged();
    partial void OnbusselfidChanging(string value);
    partial void OnbusselfidChanged();
    partial void OnlngChanging(string value);
    partial void OnlngChanged();
    partial void OnlatChanging(string value);
    partial void OnlatChanged();
    partial void OnpassgerChanging(System.Nullable<int> value);
    partial void OnpassgerChanged();
    #endregion
		
		public RealBus()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_busLineName", DbType="NVarChar(50)")]
		public string busLineName
		{
			get
			{
				return this._busLineName;
			}
			set
			{
				if ((this._busLineName != value))
				{
					this.OnbusLineNameChanging(value);
					this.SendPropertyChanging();
					this._busLineName = value;
					this.SendPropertyChanged("busLineName");
					this.OnbusLineNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BusStopsName", DbType="NVarChar(50)")]
		public string BusStopsName
		{
			get
			{
				return this._BusStopsName;
			}
			set
			{
				if ((this._BusStopsName != value))
				{
					this.OnBusStopsNameChanging(value);
					this.SendPropertyChanging();
					this._BusStopsName = value;
					this.SendPropertyChanged("BusStopsName");
					this.OnBusStopsNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stationname", DbType="NVarChar(50)")]
		public string stationname
		{
			get
			{
				return this._stationname;
			}
			set
			{
				if ((this._stationname != value))
				{
					this.OnstationnameChanging(value);
					this.SendPropertyChanging();
					this._stationname = value;
					this.SendPropertyChanged("stationname");
					this.OnstationnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_actdatetime", DbType="NVarChar(50)")]
		public string actdatetime
		{
			get
			{
				return this._actdatetime;
			}
			set
			{
				if ((this._actdatetime != value))
				{
					this.OnactdatetimeChanging(value);
					this.SendPropertyChanging();
					this._actdatetime = value;
					this.SendPropertyChanged("actdatetime");
					this.OnactdatetimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stationnum", DbType="NVarChar(50)")]
		public string stationnum
		{
			get
			{
				return this._stationnum;
			}
			set
			{
				if ((this._stationnum != value))
				{
					this.OnstationnumChanging(value);
					this.SendPropertyChanging();
					this._stationnum = value;
					this.SendPropertyChanged("stationnum");
					this.OnstationnumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_busselfid", DbType="NVarChar(50)")]
		public string busselfid
		{
			get
			{
				return this._busselfid;
			}
			set
			{
				if ((this._busselfid != value))
				{
					this.OnbusselfidChanging(value);
					this.SendPropertyChanging();
					this._busselfid = value;
					this.SendPropertyChanged("busselfid");
					this.OnbusselfidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lng", DbType="NVarChar(50)")]
		public string lng
		{
			get
			{
				return this._lng;
			}
			set
			{
				if ((this._lng != value))
				{
					this.OnlngChanging(value);
					this.SendPropertyChanging();
					this._lng = value;
					this.SendPropertyChanged("lng");
					this.OnlngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lat", DbType="NVarChar(50)")]
		public string lat
		{
			get
			{
				return this._lat;
			}
			set
			{
				if ((this._lat != value))
				{
					this.OnlatChanging(value);
					this.SendPropertyChanging();
					this._lat = value;
					this.SendPropertyChanged("lat");
					this.OnlatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passger", DbType="Int")]
		public System.Nullable<int> passger
		{
			get
			{
				return this._passger;
			}
			set
			{
				if ((this._passger != value))
				{
					this.OnpassgerChanging(value);
					this.SendPropertyChanging();
					this._passger = value;
					this.SendPropertyChanged("passger");
					this.OnpassgerChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
