#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace qdRealBusConsole
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="web")]
	public partial class qdRealBusDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertBusRealPositions(BusRealPositions instance);
    partial void UpdateBusRealPositions(BusRealPositions instance);
    partial void DeleteBusRealPositions(BusRealPositions instance);
    partial void InsertqdRealBus(qdRealBus instance);
    partial void UpdateqdRealBus(qdRealBus instance);
    partial void DeleteqdRealBus(qdRealBus instance);
    #endregion
		
		public qdRealBusDataClassesDataContext() : 
				base(global::qdRealBusConsole.Properties.Settings.Default.webConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public qdRealBusDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public qdRealBusDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public qdRealBusDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public qdRealBusDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BusRealPositions> BusRealPositions
		{
			get
			{
				return this.GetTable<BusRealPositions>();
			}
		}
		
		public System.Data.Linq.Table<qdRealBus> qdRealBus
		{
			get
			{
				return this.GetTable<qdRealBus>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BusRealPositions")]
	public partial class BusRealPositions : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _busselfid;
		
		private string _busLineName;
		
		private string _BusOnewayId;
		
		private string _BusStopsNumber;
		
		private string _BusStopsName;
		
		private string _busType;
		
		private System.Nullable<int> _stationnum;
		
		private System.Nullable<System.DateTime> _datetime;
		
		private System.Nullable<System.DateTime> _actdatetime;
		
		private string _stationname;
		
		private System.Nullable<double> _lng;
		
		private System.Nullable<double> _lat;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnbusselfidChanging(string value);
    partial void OnbusselfidChanged();
    partial void OnbusLineNameChanging(string value);
    partial void OnbusLineNameChanged();
    partial void OnBusOnewayIdChanging(string value);
    partial void OnBusOnewayIdChanged();
    partial void OnBusStopsNumberChanging(string value);
    partial void OnBusStopsNumberChanged();
    partial void OnBusStopsNameChanging(string value);
    partial void OnBusStopsNameChanged();
    partial void OnbusTypeChanging(string value);
    partial void OnbusTypeChanged();
    partial void OnstationnumChanging(System.Nullable<int> value);
    partial void OnstationnumChanged();
    partial void OndatetimeChanging(System.Nullable<System.DateTime> value);
    partial void OndatetimeChanged();
    partial void OnactdatetimeChanging(System.Nullable<System.DateTime> value);
    partial void OnactdatetimeChanged();
    partial void OnstationnameChanging(string value);
    partial void OnstationnameChanged();
    partial void OnlngChanging(System.Nullable<double> value);
    partial void OnlngChanged();
    partial void OnlatChanging(System.Nullable<double> value);
    partial void OnlatChanged();
    #endregion
		
		public BusRealPositions()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_busselfid", DbType="NVarChar(50)")]
		public string busselfid
		{
			get
			{
				return this._busselfid;
			}
			set
			{
				if ((this._busselfid != value))
				{
					this.OnbusselfidChanging(value);
					this.SendPropertyChanging();
					this._busselfid = value;
					this.SendPropertyChanged("busselfid");
					this.OnbusselfidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_busLineName", DbType="NVarChar(50)")]
		public string busLineName
		{
			get
			{
				return this._busLineName;
			}
			set
			{
				if ((this._busLineName != value))
				{
					this.OnbusLineNameChanging(value);
					this.SendPropertyChanging();
					this._busLineName = value;
					this.SendPropertyChanged("busLineName");
					this.OnbusLineNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BusOnewayId", DbType="NVarChar(50)")]
		public string BusOnewayId
		{
			get
			{
				return this._BusOnewayId;
			}
			set
			{
				if ((this._BusOnewayId != value))
				{
					this.OnBusOnewayIdChanging(value);
					this.SendPropertyChanging();
					this._BusOnewayId = value;
					this.SendPropertyChanged("BusOnewayId");
					this.OnBusOnewayIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BusStopsNumber", DbType="NVarChar(50)")]
		public string BusStopsNumber
		{
			get
			{
				return this._BusStopsNumber;
			}
			set
			{
				if ((this._BusStopsNumber != value))
				{
					this.OnBusStopsNumberChanging(value);
					this.SendPropertyChanging();
					this._BusStopsNumber = value;
					this.SendPropertyChanged("BusStopsNumber");
					this.OnBusStopsNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BusStopsName", DbType="NVarChar(50)")]
		public string BusStopsName
		{
			get
			{
				return this._BusStopsName;
			}
			set
			{
				if ((this._BusStopsName != value))
				{
					this.OnBusStopsNameChanging(value);
					this.SendPropertyChanging();
					this._BusStopsName = value;
					this.SendPropertyChanged("BusStopsName");
					this.OnBusStopsNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_busType", DbType="NChar(10)")]
		public string busType
		{
			get
			{
				return this._busType;
			}
			set
			{
				if ((this._busType != value))
				{
					this.OnbusTypeChanging(value);
					this.SendPropertyChanging();
					this._busType = value;
					this.SendPropertyChanged("busType");
					this.OnbusTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stationnum", DbType="Int")]
		public System.Nullable<int> stationnum
		{
			get
			{
				return this._stationnum;
			}
			set
			{
				if ((this._stationnum != value))
				{
					this.OnstationnumChanging(value);
					this.SendPropertyChanging();
					this._stationnum = value;
					this.SendPropertyChanged("stationnum");
					this.OnstationnumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datetime", DbType="DateTime")]
		public System.Nullable<System.DateTime> datetime
		{
			get
			{
				return this._datetime;
			}
			set
			{
				if ((this._datetime != value))
				{
					this.OndatetimeChanging(value);
					this.SendPropertyChanging();
					this._datetime = value;
					this.SendPropertyChanged("datetime");
					this.OndatetimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_actdatetime", DbType="DateTime")]
		public System.Nullable<System.DateTime> actdatetime
		{
			get
			{
				return this._actdatetime;
			}
			set
			{
				if ((this._actdatetime != value))
				{
					this.OnactdatetimeChanging(value);
					this.SendPropertyChanging();
					this._actdatetime = value;
					this.SendPropertyChanged("actdatetime");
					this.OnactdatetimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stationname", DbType="NVarChar(50)")]
		public string stationname
		{
			get
			{
				return this._stationname;
			}
			set
			{
				if ((this._stationname != value))
				{
					this.OnstationnameChanging(value);
					this.SendPropertyChanging();
					this._stationname = value;
					this.SendPropertyChanged("stationname");
					this.OnstationnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lng", DbType="Float")]
		public System.Nullable<double> lng
		{
			get
			{
				return this._lng;
			}
			set
			{
				if ((this._lng != value))
				{
					this.OnlngChanging(value);
					this.SendPropertyChanging();
					this._lng = value;
					this.SendPropertyChanged("lng");
					this.OnlngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lat", DbType="Float")]
		public System.Nullable<double> lat
		{
			get
			{
				return this._lat;
			}
			set
			{
				if ((this._lat != value))
				{
					this.OnlatChanging(value);
					this.SendPropertyChanging();
					this._lat = value;
					this.SendPropertyChanged("lat");
					this.OnlatChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.qdRealBus")]
	public partial class qdRealBus : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _busLineName;
		
		private string _BusStopsNumber;
		
		private string _BusStopsName;
		
		private string _stationname;
		
		private string _datetime;
		
		private System.Nullable<System.DateTime> _actdatetime;
		
		private string _stationnum;
		
		private string _busselfid;
		
		private System.Nullable<double> _lng;
		
		private System.Nullable<double> _lat;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnbusLineNameChanging(string value);
    partial void OnbusLineNameChanged();
    partial void OnBusStopsNumberChanging(string value);
    partial void OnBusStopsNumberChanged();
    partial void OnBusStopsNameChanging(string value);
    partial void OnBusStopsNameChanged();
    partial void OnstationnameChanging(string value);
    partial void OnstationnameChanged();
    partial void OndatetimeChanging(string value);
    partial void OndatetimeChanged();
    partial void OnactdatetimeChanging(System.Nullable<System.DateTime> value);
    partial void OnactdatetimeChanged();
    partial void OnstationnumChanging(string value);
    partial void OnstationnumChanged();
    partial void OnbusselfidChanging(string value);
    partial void OnbusselfidChanged();
    partial void OnlngChanging(System.Nullable<double> value);
    partial void OnlngChanged();
    partial void OnlatChanging(System.Nullable<double> value);
    partial void OnlatChanged();
    #endregion
		
		public qdRealBus()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_busLineName", DbType="NVarChar(50)")]
		public string busLineName
		{
			get
			{
				return this._busLineName;
			}
			set
			{
				if ((this._busLineName != value))
				{
					this.OnbusLineNameChanging(value);
					this.SendPropertyChanging();
					this._busLineName = value;
					this.SendPropertyChanged("busLineName");
					this.OnbusLineNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BusStopsNumber", DbType="NVarChar(50)")]
		public string BusStopsNumber
		{
			get
			{
				return this._BusStopsNumber;
			}
			set
			{
				if ((this._BusStopsNumber != value))
				{
					this.OnBusStopsNumberChanging(value);
					this.SendPropertyChanging();
					this._BusStopsNumber = value;
					this.SendPropertyChanged("BusStopsNumber");
					this.OnBusStopsNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BusStopsName", DbType="NVarChar(50)")]
		public string BusStopsName
		{
			get
			{
				return this._BusStopsName;
			}
			set
			{
				if ((this._BusStopsName != value))
				{
					this.OnBusStopsNameChanging(value);
					this.SendPropertyChanging();
					this._BusStopsName = value;
					this.SendPropertyChanged("BusStopsName");
					this.OnBusStopsNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stationname", DbType="NVarChar(50)")]
		public string stationname
		{
			get
			{
				return this._stationname;
			}
			set
			{
				if ((this._stationname != value))
				{
					this.OnstationnameChanging(value);
					this.SendPropertyChanging();
					this._stationname = value;
					this.SendPropertyChanged("stationname");
					this.OnstationnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datetime", DbType="NVarChar(50)")]
		public string datetime
		{
			get
			{
				return this._datetime;
			}
			set
			{
				if ((this._datetime != value))
				{
					this.OndatetimeChanging(value);
					this.SendPropertyChanging();
					this._datetime = value;
					this.SendPropertyChanged("datetime");
					this.OndatetimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_actdatetime", DbType="DateTime")]
		public System.Nullable<System.DateTime> actdatetime
		{
			get
			{
				return this._actdatetime;
			}
			set
			{
				if ((this._actdatetime != value))
				{
					this.OnactdatetimeChanging(value);
					this.SendPropertyChanging();
					this._actdatetime = value;
					this.SendPropertyChanged("actdatetime");
					this.OnactdatetimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stationnum", DbType="NVarChar(50)")]
		public string stationnum
		{
			get
			{
				return this._stationnum;
			}
			set
			{
				if ((this._stationnum != value))
				{
					this.OnstationnumChanging(value);
					this.SendPropertyChanging();
					this._stationnum = value;
					this.SendPropertyChanged("stationnum");
					this.OnstationnumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_busselfid", DbType="NVarChar(50)")]
		public string busselfid
		{
			get
			{
				return this._busselfid;
			}
			set
			{
				if ((this._busselfid != value))
				{
					this.OnbusselfidChanging(value);
					this.SendPropertyChanging();
					this._busselfid = value;
					this.SendPropertyChanged("busselfid");
					this.OnbusselfidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lng", DbType="Float")]
		public System.Nullable<double> lng
		{
			get
			{
				return this._lng;
			}
			set
			{
				if ((this._lng != value))
				{
					this.OnlngChanging(value);
					this.SendPropertyChanging();
					this._lng = value;
					this.SendPropertyChanged("lng");
					this.OnlngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lat", DbType="Float")]
		public System.Nullable<double> lat
		{
			get
			{
				return this._lat;
			}
			set
			{
				if ((this._lat != value))
				{
					this.OnlatChanging(value);
					this.SendPropertyChanging();
					this._lat = value;
					this.SendPropertyChanged("lat");
					this.OnlatChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
