<?xml version="1.0" encoding="utf-8"?><Database Name="web" Class="qdRealBusDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=222.195.148.120;Initial Catalog=web;Persist Security Info=True;User ID=web" SettingsObjectName="qdRealBusConsole.Properties.Settings" SettingsPropertyName="webConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BusRealPositions" Member="BusRealPositions">
    <Type Name="BusRealPositions">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="busselfid" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="busLineName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BusOnewayId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BusStopsNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BusStopsName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="busType" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="stationnum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="datetime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="actdatetime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="stationname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="lng" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="lat" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.qdRealBus" Member="qdRealBus">
    <Type Name="qdRealBus">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="busLineName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BusStopsNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BusStopsName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="stationname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="datetime" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="actdatetime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="stationnum" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="busselfid" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="lng" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="lat" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
</Database>